export let config = {
    'splash': {
        'name': 'splash',
        'route': '/splash',
        'page_category': 'splashpage',
        'page_name': 'prelogin:splashpage',
        'page_section': 'prelogin',
        'page_subcategory_level_1': 'splashpage',
        'page_subcategory_level_2': '',
        'page_subcategory_level_3': '',
        'page_screen': 'splashpage',
        'page_typology': 'principal',
        'loadChildren': '../app/splash/splash.module#SplashModule'
    },
    'demo': {
        'name': 'demo',
        'route': '/demo',
        'loadChildren': '../app/demo/demo.module#DemoModule'
    },
    /** this is capital to match routes for tagging  */
    'Inbox': {
        'name': 'Inbox',
        'route': '/Inbox',
        'loadChildren': '../app/inbox-messages/inbox-messages.module#InboxMessagesModule',
        'permissionList': ['Authorized'],
        /** this is capital to match routes for tagging  */
        'InboxListing': {
            'name': 'InboxListing',
            'route': '/Inbox/InboxListing',
            'deeplink': true,
            'page_category': 'bandeja de entrada',
            'page_name': 'mensajes:bandeja de entrada',
            'page_section': 'mensajes',
            'page_subcategory_level_1': 'bandeja de entrada',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'bandeja de entrada',
            'page_typology': 'principal'
        },
        'details': {

            'name': 'details',
            'route': '/Inbox/details',
            'page_category': 'bandeja de entrada',
            'page_name': 'mensajes:bandeja de entrada:detalle de mensaje',
            'page_section': 'mensajes',
            'page_subcategory_level_1': 'bandeja de entrada',
            'page_subcategory_level_2': 'detalle de mensaje',
            'page_subcategory_level_3': '',
            'page_screen': 'detalle de mensaje',
            'page_typology': 'principal'
        },
        'configration': {

            'name': 'configration',
            'route': '/Inbox/configration',
        },
    },
    'login': {
        'name': 'login',
        'route': '/login',
        'page_category': 'login',
        'page_name': 'login:login',
        'page_section': 'login',
        'page_subcategory_level_1': 'login',
        'page_subcategory_level_2': '',
        'page_subcategory_level_3': '',
        'page_screen': 'login',
        'page_typology': 'principal',
        'loadChildren': '../app/login/login.module#LoginModule',
        'loginSeibelRedirection': {
            'name': 'loginSeibelRedirection',
            'route': '/login/loginSeibelRedirection',
        }
    },
    'companyChooser': {
        'name': 'companyChooser',
        'route': '/login/companyChooser',
        'page_category': 'login',
        'page_name': 'login:companyChooser',
        'page_section': 'login',
        'page_subcategory_level_1': 'login',
        'page_subcategory_level_2': 'companyChooser',
        'page_subcategory_level_3': '',
        'page_screen': 'companyChooser',
        'page_typology': 'overlay',
        'permissionList': ['Authorized']
    },
    'dashboard': {
        'name': 'dashboard',
        'route': '/dashboard',
        'page_category': 'home',
        'page_name': 'dashboard:home',
        'page_section': 'dashboard',
        'page_subcategory_level_1': 'home',
        'page_subcategory_level_2': '',
        'page_subcategory_level_3': '',
        'page_screen': 'home',
        'page_typology': 'principal',
        'loadChildren': '../app/dashboard/dashboard.module#DashboardModule',
        'permissionList': ['Authorized'],
        'deeplink': true
    },
    'myAccount': {
        'name': 'myAccount',
        'route': '/myAccount',
        'page_category': 'myAccount',
        'page_name': 'myAccount:myAccount',
        'page_section': 'myAccount',
        'page_subcategory_level_1': '',
        'page_subcategory_level_2': '',
        'page_subcategory_level_3': '',
        'page_screen': 'myAccount',
        'page_typology': 'principal',
        'permissionList': ['Authorized'],
        'loadChildren': '../app/my-account/my-account.module#MyAccountModule',
        'OverviewScreen': {
            'name': 'OverviewScreen',
            'route': '/myAccount/OverviewScreen',
            'page_category': 'factura de dispositivos',
            'page_name': 'facturas:factura de dispositivos:resumen de facturas de dispositivo',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'factura de dispositivos',
            'page_subcategory_level_2': 'resumen de facturas de dispositivo',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de facturas de dispositivo',
            'page_typology': 'principal',
            'deeplink': true
        },
        'permissionAndPrefrence': {
            'name': 'permissionAndPrefrence',
            'route': '/myAccount/permissionAndPrefrence',
            'deeplink': true,
        },
        'permissions': {
            'name': 'permissions',
            'route': '/myAccount/permissions',
            'deeplink': true,
        },
        'prefrences': {
            'name': 'prefrences',
            'route': '/myAccount/prefrences',
            'deeplink': true,
        },
        'editUserDetails': {
            'name': 'YourDetails/EdituserDetail',
            'route': '/myAccount/YourDetails/EdituserDetails',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar datos personales',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar datos personales',
            'page_subcategory_level_3': '',
            'page_screen': 'editar datos personales',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editDetails': {
            'name': 'editDetails',
            'route': '/myAccount/editDetails',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar datos personales',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar datos personales',
            'page_subcategory_level_3': '',
            'page_screen': 'editar datos personales',
            'page_typology': 'principal',
            'deeplink': true
        },
        'userDetails': {
            'name': 'YourDetails/MainPage',
            'route': '/myAccount/YourDetails/MainPage',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:resumen de tus datos',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'resumen de tus datos',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de tus datos',
            'page_typology': 'principal',
            'deeplink': true
        },
        'details': {
            'name': 'details',
            'route': '/myAccount/details',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:resumen de tus datos',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'resumen de tus datos',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de tus datos',
            'page_typology': 'principal',
            'deeplink': true
        },
        'nif': {
            'name': 'nif',
            'route': '/myAccount/nif',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar datos personales:editar dni',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar datos personales',
            'page_subcategory_level_3': 'editar dni',
            'page_screen': 'editar dni',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editNif': {
            'name': 'YourDetails/EdituserDetails/EditDNI',
            'route': '/myAccount/YourDetails/EdituserDetails/EditDNI',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar datos personales:editar dni',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar datos personales',
            'page_subcategory_level_3': 'editar dni',
            'page_screen': 'editar dni',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editAddress': {
            'name': 'editAddress',
            'route': '/myAccount/editAddress',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar direccion',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar direccion',
            'page_subcategory_level_3': '',
            'page_screen': 'editar direccion',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editUserAddress': {
            'name': 'YourDetails/EditAddress',
            'route': '/myAccount/YourDetails/EditAddress',
            'page_category': 'tus datos',
            'page_name': 'mi cuenta:tus datos:editar direccion',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'tus datos',
            'page_subcategory_level_2': 'editar direccion',
            'page_subcategory_level_3': '',
            'page_screen': 'editar direccion',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editAddressPayment': {
            'name': 'editAddressPayment',
            'route': '/myAccount/editAddressPayment',
            'page_category': 'metodos de pago',
            'page_name': 'mi cuenta:metodos de pago:editar dirección de facturación',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'metodos de pago',
            'page_subcategory_level_2': 'editar dirección de facturación',
            'page_subcategory_level_3': '',
            'page_screen': 'editar dirección de facturación',
            'page_typology': 'principal',
        },
        'suggestedAddress': {
            'name': 'suggestedAddress',
            'route': '/myAccount/suggestedAddress',
            'page_category': 'metodos de pago',
            'page_name': 'mi cuenta:metodos de pago:editar dirección de facturación:normalizar datos',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'metodos de pago',
            'page_subcategory_level_2': 'editar dirección de facturación',
            'page_subcategory_level_3': 'normalizar datos',
            'page_screen': 'normalizar datos',
            'page_typology': 'principal',
        },
        'accessInfo': {
            'name': 'accessInfo',
            'route': '/myAccount/accessInfo',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:resumen de acceso a mi vodafone',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'resumen de acceso a mi vodafone',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de acceso a mi vodafone',
            'page_typology': 'principal',
            'deeplink': true
        },
        'serviceAccessInfo': {
            'name': 'Serviceaccess/MainPage',
            'route': '/myAccount/Serviceaccess/MainPage',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:resumen de acceso a mi vodafone',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'resumen de acceso a mi vodafone',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de acceso a mi vodafone',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editPassword': {
            'name': 'editPassword',
            'route': '/myAccount/editPassword',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:editar clave',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'editar clave',
            'page_subcategory_level_3': '',
            'page_screen': 'editar clave',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editUserPassword': {
            'name': 'Serviceaccess/Edituserpassword',
            'route': '/myAccount/Serviceaccess/Edituserpassword',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:editar clave',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'editar clave',
            'page_subcategory_level_3': '',
            'page_screen': 'editar clave',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editEmail': {
            'name': 'editEmail',
            'route': '/myAccount/editEmail',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:editar usuario',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'editar usuario',
            'page_subcategory_level_3': '',
            'page_screen': 'editar usuario',
            'page_typology': 'principal',
            'deeplink': true
        },
        'editUserName': {
            'name': 'Serviceaccess/Editusername',
            'route': '/myAccount/Serviceaccess/Editusername',
            'page_category': 'acceso a mi vodafone',
            'page_name': 'mi cuenta:acceso a mi vodafone:editar usuario',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'acceso a mi vodafone',
            'page_subcategory_level_2': 'editar usuario',
            'page_subcategory_level_3': '',
            'page_screen': 'editar usuario',
            'page_typology': 'principal',
            'deeplink': true
        },
        'bankInfo': {
            'name': 'bankInfo',
            'route': '/myAccount/bankInfo',
            'page_category': 'metodos de pago',
            'page_name': 'mi cuenta:metodos de pago:editar datos bancarios',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'metodos de pago',
            'page_subcategory_level_2': 'editar datos bancarios',
            'page_subcategory_level_3': '',
            'page_screen': 'editar datos bancarios',
            'page_typology': 'principal',
        },
        'otp': {
            'name': 'otp',
            'route': '/myAccount/otp',
            'page_category': '',
            'page_name': '',
            'page_section': '',
            'page_subcategory_level_1': '',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': '',
            'page_typology': 'principal',
        },
        'contracts': {
            'name': 'contracts',
            'route': '/myAccount/contracts',
            'page_category': 'mis contratos',
            'page_name': 'mi cuenta:mis contratos:resumen de mis contratos',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'mis contratos',
            'page_subcategory_level_2': 'resumen de mis contratos',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de mis contratos',
            'page_typology': 'principal',
            'deeplink': true
        },
        'myContracts': {
            'name': 'Mycontracts/MainPage',
            'route': '/myAccount/Mycontracts/MainPage',
            'page_category': 'mis contratos',
            'page_name': 'mi cuenta:mis contratos:resumen de mis contratos',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'mis contratos',
            'page_subcategory_level_2': 'resumen de mis contratos',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de mis contratos',
            'page_typology': 'principal',
            'deeplink': true
        },
        'paymentMethods': {
            'name': 'paymentMethods',
            'route': '/myAccount/paymentMethods',
            'page_category': 'metodos de pago',
            'page_name': 'mi cuenta:metodos de pago:resumen de metodos de pago',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'metodos de pago',
            'page_subcategory_level_2': 'resumen de metodos de pago',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de metodos de pago',
            'page_typology': 'principal'
        },
        'userPaymentMethods': {
            'name': 'Paymethods/MainPage',
            'route': '/myAccount/Paymethods/MainPage',
            'page_category': 'metodos de pago',
            'page_name': 'mi cuenta:metodos de pago:resumen de metodos de pago',
            'page_section': 'mi cuenta',
            'page_subcategory_level_1': 'metodos de pago',
            'page_subcategory_level_2': 'resumen de metodos de pago',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de metodos de pago',
            'page_typology': 'principal'
        },
        'billingAccounts': {
            'name': 'billingAccounts',
            'route': '/myAccount/billingAccounts',
            'page_category': 'myAccount',
            'page_name': 'myAccount:OverviewScreen:paymentMethods:billingAccounts',
            'page_section': 'myAccount',
            'page_subcategory_level_1': 'OverviewScreen',
            'page_subcategory_level_2': 'paymentMethods',
            'page_subcategory_level_3': 'billingAccounts',
            'page_screen': 'billingAccounts',
            'page_typology': 'principal'
        },
        'PermissionsAndAuthorizations': {
            'name': 'PermissionsAndAuthorizations',
            'route': '/myAccount/PermissionsAndAuthorizations',
            'deeplink': true,
            'page_category': 'myAccount',
            'page_name': 'myAccount:OverviewScreen:PermissionsAndAuthorizations',
            'page_section': 'myAccount',
            'page_subcategory_level_1': 'myAccount',
            'page_subcategory_level_2': 'OverviewScreen',
            'page_subcategory_level_3': 'PermissionsAndAuthorizations',
            'page_screen': 'PermissionsAndAuthorizations',
            'page_typology': 'principal'
        },
        'addNewAuthorized': {
            'name': 'addNewAuthorized',
            'route': '/myAccount/addNewAuthorized',
            'page_category': 'myAccount',
            'page_name': 'myAccount:OverviewScreen:addNewAuthorized',
            'page_section': 'myAccount',
            'page_subcategory_level_1': 'myAccount',
            'page_subcategory_level_2': 'OverviewScreen',
            'page_subcategory_level_3': 'addNewAuthorized',
            'page_screen': 'addNewAuthorized',
            'page_typology': 'principal'
        }
    },
    'serviceSelectorNonDashboard': {
        'name': 'serviceSelector',
        'route': '/serviceSelector',
        'permissionList': ['Authorized'],
    },
    'ProductsAndServices': {
        'name': 'ProductsAndServices',
        'route': '/ProductsAndServices',
        'permissionList': ['Authorized'],
        'page_category': 'ProductsAndServices',
        'page_name': 'ProductsAndServices:ProductsAndServices',
        'page_section': 'ProductsAndServices',
        'page_subcategory_level_1': '',
        'page_subcategory_level_2': '',
        'page_subcategory_level_3': '',
        'page_screen': 'ProductsAndServices',
        'page_typology': 'principal',
        'loadChildren': '../app/products-and-services/products-and-services.module#ProductsAndServicesModule',
        'landing': {
            'name': 'MainScreen',
            'route': '/ProductsAndServices/MainScreen',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'MainScreen',
            'page_typology': 'principal'
        },
        'MainScreen': {
            'name': 'MainScreen',
            'route': '/ProductsAndServices/MainScreen',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'MainScreen',
            'page_typology': 'principal'
        },
        'onlineTvlanding': {
            'name': 'PlanDetails/OnlineTV',
            'route': '/ProductsAndServices/PlanDetails/OnlineTV',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'MainScreen',
            'page_typology': 'principal'
        },
        'enjoyMoreDetails': {
            'name': 'enjoyMoreDetails',
            'route': '/ProductsAndServices/enjoyMoreDetails',
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'enjoyMoreDetails',
            'page_typology': 'detalle'
        },
        'enjoyMoreDetailsChat': {
            'name': 'enjoymore/Chatpass',
            'route': '/ProductsAndServices/enjoymore/Chatpass',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'enjoyMoreDetails',
            'page_typology': 'detalle'
        },
        'enjoyMoreDetailsSocial': {
            'name': 'enjoymore/Socialpass',
            'route': '/ProductsAndServices/enjoymore/Socialpass',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'enjoyMoreDetails',
            'page_typology': 'detalle'
        },
        'enjoyMoreDetailsVideo': {
            'name': 'enjoymore/Videopass',
            'route': '/ProductsAndServices/enjoymore/Videopass',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'enjoyMoreDetails',
            'page_typology': 'detalle'
        },
        'enjoyMoreDetailsMusic': {
            'name': 'enjoymore/Musicpass',
            'route': '/ProductsAndServices/enjoymore/Musicpass',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'enjoyMoreDetails',
            'page_typology': 'detalle'
        },
        'extraListDetails': {
            'name': 'extraListDetails',
            'route': '/ProductsAndServices/extraListDetails',
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList:extrasList:extraListDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'extrasCategoryList',
            'page_subcategory_level_2': 'extrasList',
            'page_subcategory_level_3': 'extraListDetails',
            'page_screen': 'extraListDetails',
            'page_typology': 'detalle'
        },
        'extrasCategoryList': {
            'name': 'extrasCategoryList',
            'route': '/ProductsAndServices/extrasCategoryList',
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': '',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'extrasDataCategoryList': {
            'name': 'Extras/Data/ExtraDetails',
            'route': '/ProductsAndServices/Extras/Data/ExtraDetails',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': '',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'extrasMinutesCategoryList': {
            'name': 'Extras/Minutes/ExtraDetails',
            'route': '/ProductsAndServices/Extras/Minutes/ExtraDetails',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': '',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'extrasSMSCategoryList': {
            'name': 'Extras/SMS/ExtraDetails',
            'route': '/ProductsAndServices/Extras/SMS/ExtraDetails',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': '',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'termsAndConditions': {
            'name': 'termsAndConditions',
            'route': '/ProductsAndServices/termsAndConditions',
            'page_name': 'ProductsAndServices:MainScreen:enjoyMoreDetails:termsAndConditions',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'enjoyMoreDetails',
            'page_subcategory_level_3': 'termsAndConditions',
            'page_screen': 'termsAndConditions',
            'page_typology': 'principal'
        },
        'extrasList': {
            'name': 'extrasList',
            'route': '/ProductsAndServices/extrasList',
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList:extrasList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': 'extrasList',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'extrasListDeep': {
            'name': 'Extras/MainScreen',
            'route': '/ProductsAndServices/Extras/MainScreen',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:extrasCategoryList:extrasList',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'extrasCategoryList',
            'page_subcategory_level_3': 'extrasList',
            'page_screen': 'extrasList',
            'page_typology': 'principal'
        },
        'details': {
            'name': 'details',
            'route': '/ProductsAndServices/details',
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:details',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': '',
            'page_screen': 'details',
            'page_typology': 'detalle'
        },
        'detailsDeep': {
            'name': 'PlanDetails',
            'route': '/ProductsAndServices/PlanDetails',
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:details',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': '',
            'page_screen': 'details',
            'page_typology': 'detalle',
            'deeplink': true
        },
        'tvDetailsDeep': {
            'name': 'PlanDetails/TV',
            'route': '/ProductsAndServices/PlanDetails/TV',
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:details',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': '',
            'page_screen': 'details',
            'page_typology': 'detalle',
            'deeplink': true
        },
        'special': {
            'name': 'special',
            'route': '/ProductsAndServices/special',
            'page_name': 'ProductsAndServices:MainScreen:details:special',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': 'special',
            'page_screen': 'details',
            'page_typology': 'detalle'
        },
        'specialCall': {
            'name': 'PlanDetails/Specialcallprices',
            'route': '/ProductsAndServices/PlanDetails/Specialcallprices',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:details:special',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': 'special',
            'page_screen': 'details',
            'page_typology': 'detalle'
        },
        'specialSMS': {
            'name': 'PlanDetails/Specialsmsprices',
            'route': '/ProductsAndServices/PlanDetails/Specialsmsprices',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:details:special',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'details',
            'page_subcategory_level_3': 'special',
            'page_screen': 'details',
            'page_typology': 'detalle'
        },
        'manageWorryFree': {
            'name': 'manageWorryFree',
            'route': '/ProductsAndServices/manageWorryFree',
            'page_name': 'ProductsAndServices:MainScreen:manageWorryFree',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'manageWorryFree',
            'page_subcategory_level_3': '',
            'page_screen': 'manageWorryFree',
            'page_typology': 'principal'
        },
        'worryFreeMain': {
            'name': 'worryfree/MainPage',
            'route': '/ProductsAndServices/worryfree/MainPage',
            'deeplink': true,
            'page_category': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'MainScreen',
            'page_typology': 'principal'
        },
        'channelDetails': {
            'name': 'channelDetails',
            'route': '/ProductsAndServices/channelDetails',
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsBaby': {
            'name': 'PlanDetails/ExtraTVChannelDetails/BabyTV',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/BabyTV',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsVodafoneLiga': {
            'name': 'PlanDetails/ExtraTVChannelDetails/VodafoneLiga',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/VodafoneLiga',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsCasaVision': {
            'name': 'PlanDetails/ExtraTVChannelDetails/CasaVision',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/CasaVision',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsAdults': {
            'name': 'PlanDetails/ExtraTVChannelDetails/Adults',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/Adults',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsDark': {
            'name': 'PlanDetails/ExtraTVChannelDetails/Dark',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/Dark',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelDetailsFootball': {
            'name': 'PlanDetails/ExtraTVChannelDetails/Football',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelDetails/Football',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelList:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelList',
            'page_subcategory_level_3': 'channelDetails',
            'page_screen': 'channelDetails',
            'page_typology': 'detalle'
        },
        'channelList': {
            'name': 'channelList',
            'route': '/ProductsAndServices/channelList',
            'page_name': 'ProductsAndServices:MainScreen:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'channelList',
            'page_typology': 'principal'
        },
        'channelListDeep': {
            'name': 'PlanDetails/ExtraTVChannelListing',
            'route': '/ProductsAndServices/PlanDetails/ExtraTVChannelListing',
            'deeplink': true,
            'page_name': 'ProductsAndServices:MainScreen:channelDetails',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'channelDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'channelList',
            'page_typology': 'principal'
        },
        'onlineTvDetails': {
            'name': 'onlineTvDetails',
            'route': '/ProductsAndServices/onlineTvDetails',
            'page_section': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:onlineTvDetails',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'onlineTvDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'channelList',
            'page_typology': 'detalle'
        },
        'onlineTvDetailsUsername': {
            'name': 'PlanDetails/OnlineTV/changeusername',
            'route': '/ProductsAndServices/PlanDetails/OnlineTV/changeusername',
            'deeplink': true,
            'page_section': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:onlineTvDetails',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'onlineTvDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'channelList',
            'page_typology': 'detalle'
        },
        'onlineTvDetailsPassword': {
            'name': 'PlanDetails/OnlineTV/changepassword',
            'route': '/ProductsAndServices/PlanDetails/OnlineTV/changepassword',
            'deeplink': true,
            'page_section': 'ProductsAndServices',
            'page_name': 'ProductsAndServices:MainScreen:onlineTvDetails',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'onlineTvDetails',
            'page_subcategory_level_3': '',
            'page_screen': 'channelList',
            'page_typology': 'detalle'
        },
        'changeUsername': {
            'name': 'changeUsername',
            'route': '/ProductsAndServices/changeUsername',
            'page_name': 'ProductsAndServices:MainScreen:onlineTvDetail:changeUsername',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'onlineTvDetail',
            'page_subcategory_level_3': 'changeUsername',
            'page_screen': 'changeUsername',
            'page_typology': 'detalle'
        },
        'onlineTvDetail': {
            'name': 'onlineTvDetail',
            'route': '/ProductsAndServices/onlineTvDetail',
            'page_name': 'ProductsAndServices:MainScreen:onlineTvDetail',
            'page_section': 'ProductsAndServices',
            'page_subcategory_level_1': 'MainScreen',
            'page_subcategory_level_2': 'onlineTvDetail',
            'page_subcategory_level_3': '',
            'page_screen': 'onlineTvDetail',
            'page_typology': 'detalle'
        },
        'entertainmentDetails': {
            'name': 'entertainmentDetails',
            'route': '/ProductsAndServices/entertainmentDetails'
        },
        'entertainmentListing': {
            'name': 'Extras/Entertainment/Listing',
            'route': '/ProductsAndServices/Extras/Entertainment/Listing',
            'deeplink': true
        }, 'editDataSharing': {
            'name': 'editDataSharing',
            'route': '/ProductsAndServices/editDataSharing',
            'deeplink': true,
        }


    },
    'commitmentContracts': {
        'name': 'commitmentContracts',
        'route': '/commitmentContracts',
        'permissionList': ['Authorized'],
        'loadChildren': '../app/commitment-contracts/commitment-contracts.module#CommitmentContractsModule',
        'siteSelector': {
            'name': 'siteSelector',
            'route': '/commitmentContracts/siteSelector',
        },
        /** cc stands for Commitment Contract */
        'ccServiceSelector': {
            'name': 'ccServiceSelector',
            'route': '/commitmentContracts/ccServiceSelector',
        },
        'contracts': {
            'name': 'contracts',
            'route': '/commitmentContracts/contracts',
        }
    },
    'TopUp': {
        'name': 'TopUp',
        'route': '/TopUp',
        'permissionList': ['Authorized'],
        'loadChildren': '../app/top-up/top-up.module#TopUpModule',
        'topUpHistory': {
            'name': 'topUpHistory',
            'route': '/TopUp/topUpHistory',
            'deeplink': true,
            'page_category': 'historico de recargas',
            'page_name': 'recargas:historico de recargas',
            'page_section': 'recargas',
            'page_subcategory_level_1': 'historico de recargas',
            'page_subcategory_level_2': '',
            'page_subcategory_level_3': '',
            'page_screen': 'historico de recargas',
            'page_typology': 'principal'
        },
        'topUpCurrentSpendings': {
            'name': 'currentSpendingHistory',
            'route': '/TopUp/currentSpendingHistory',
            'deeplink': true
        },
        'topUpPrepaidservice': {
            'name': 'topUpPrepaidservice',
            'route': '/TopUp/topUpPrepaidservice',
            'deeplink': true,
            'page_category': 'realizar recarga',
            'page_name': 'recargas:realizar recarga:inicio de recarga',
            'page_section': 'recargas',
            'page_subcategory_level_1': 'realizar recarga',
            'page_subcategory_level_2': 'inicio de recarga',
            'page_subcategory_level_3': '',
            'page_screen': 'inicio de recarga',
            'page_typology': 'principal'
        }
    },
    'billing': {
        'name': 'billing',
        'route': '/billing',
        'permissionList': ['Authorized'],
        'loadChildren': '../app/billing/billing.module#BillingModule',
        'billingOverview': {
            'name': 'billingOverview',
            'route': '/billing/billingOverview',
            'page_category': 'mis facturas',
            'page_name': 'facturas:mis facturas:resumen de cuentas',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'mis facturas',
            'page_subcategory_level_2': 'resumen de cuentas',
            'page_subcategory_level_3': '',
            'page_screen': 'resumen de cuentas',
            'page_typology': 'principal',

            'deeplink': true
        },
        'billingDetails': {
            'name': 'billingDetails',
            'route': '/billing/billingDetails',
            'page_category': 'mis facturas',
            'page_name': 'facturas:mis facturas:detalle de factura',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'mis facturas',
            'page_subcategory_level_2': 'detalle de factura',
            'page_subcategory_level_3': '',
            'page_screen': 'detalle de factura',
            'page_typology': 'principal',
            'deeplink': true
        },
        'billingDetailsServiceUsages': {
            'name': 'billingDetailsServiceUsages',
            'route': '/billing/billingDetailsServiceUsages',
            'page_category': 'mis facturas',
            'page_name': 'facturas:mis facturas:detalle de factura:detalle de consumo',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'mis facturas',
            'page_subcategory_level_2': 'detalle de factura',
            'page_subcategory_level_3': 'detalle de consumo',
            'page_screen': 'detalle de consumo',
            'page_typology': 'principal',
            'deeplink': true
        },
        'creditNotes': {
            'name': 'creditNotes',
            'route': '/billing/creditNotes'
        },
        'deviceInvoice': {
            'name': 'deviceInvoice',
            'route': '/billing/deviceInvoice',
            'deeplink': true
        },
        'billingDetailsBillShock': {
            'name': 'billingDetailsBillShock',
            'route': '/billing/billingDetailsBillShock',
            'deeplink': true
        },
        'billingDetailsBillShockSummery': {
            'name': 'billingDetailsBillShockSummery',
            'route': 'billing/billingDetailsBillShockSummery'
        },
        'billConfig': {
            'name': 'billConfig',
            'route': '/billing/billConfig',
            'deeplink': true,
            'page_category': 'configuracion de factura',
            'page_name': 'facturas:configuracion de factura:seleccionar cuenta',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'configuracion de factura',
            'page_subcategory_level_2': 'seleccionar cuenta',
            'page_subcategory_level_3': '',
            'page_screen': 'seleccionar cuenta',
            'page_typology': 'principal'
        },
        'eBill': {
            'name': 'eBill',
            'route': '/billing/eBill',
            'deeplink': true,
            'page_category': 'configuracion de factura',
            'page_name': 'facturas:configuracion de factura:opciones',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'configuracion de factura',
            'page_subcategory_level_2': 'opciones',
            'page_subcategory_level_3': '',
            'page_screen': 'opciones',
            'page_typology': 'principal'
        },
        'currentConsumption': {
            'name': 'currentConsumption',
            'route': '/billing/currentConsumption'
        },
        'billPayment': {
            'name': 'billPayment',
            'route': '/billing/billPayment',
            'deeplink': true
        },
        'billPaymentDetails': {
            'name': 'billPaymentDetails',
            'route': '/billing/billPaymentDetails',
            'deeplink': true,
            'page_category': 'pago de facturas',
            'page_name': 'facturas:pago de facturas:estado de mis facturas',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'pago de facturas',
            'page_subcategory_level_2': 'estado de mis facturas',
            'page_subcategory_level_3': '',
            'page_screen': 'estado de mis facturas',
            'page_typology': 'principal'
        },
        'noBills': {
            'name': 'noBills',
            'route': '/billing/noBills',
            'page_category': 'mis facturas',
            'page_name': 'facturas:mis facturas:no hay facturas disponibles',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'mis facturas',
            'page_subcategory_level_2': 'no hay facturas disponibles',
            'page_subcategory_level_3': '',
            'page_screen': 'no hay facturas disponibles',
            'page_typology': 'principal',

        },
        'billPaymentReady': {
            'name': 'billPaymentReady',
            'route': '/billing/billPaymentReady',
            'page_category': 'pago de facturas',
            'page_name': 'facturas:pago de facturas:detalle de pago de factura',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'pago de facturas',
            'page_subcategory_level_2': 'detalle de pago de factura',
            'page_subcategory_level_3': '',
            'page_screen': 'detalle de pago de factura',
            'page_typology': 'principal'
        },
        'billPaymentProcess': {
            'name': 'billPaymentProcess',
            'route': '/billing/billPaymentProcess',
            'page_category': 'pago de facturas',
            'page_name': 'facturas:pago de facturas:formulario de pago',
            'page_section': 'facturas',
            'page_subcategory_level_1': 'pago de facturas',
            'page_subcategory_level_2': 'formulario de pago',
            'page_subcategory_level_3': '',
            'page_screen': 'formulario de pago',
            'page_typology': 'principal'
        },
        'billPaymentMethod': {
            'name': 'otherPaymentMethod',
            'route': '/billing/otherPaymentMethod'
        }
    },
    'verifyEmail': {
        'name': 'verifyEmail',
        'route': '/verifyEmail',
        'loadChildren': '../app/verify-email/verify-email.module#VerifyEmailModule',
        'verifyPdf': {
            'name': 'verifyPdf',
            'route': '/verifyEmail/verifyPdf',
            'deeplink': true
        }
    },
    'serviceSettings': {
        'name': 'serviceSettings',
        'route': '/serviceSettings',
        'permissionList': ['Authorized'],
        'loadChildren': '../app/service-settings/service-settings.module#ServiceSettingsModule',
        'navigators': {
            'name': 'navigators',
            'route': '/serviceSettings/navigators',
            'deeplink': true
        },
        'pinpuk': {
            'name': 'pinpuk',
            'route': '/serviceSettings/pinpuk',
            'deeplink': true
        },
        'unlock': {
            'name': 'unlock',
            'route': '/serviceSettings/unlock',
            'deeplink': true
        }
    },
    'retry': {
        'name': 'retry',
        'route': '/retry',
        'deeplink': false
    }
}

